### ISSUE TITLE
Embedding isn't working

### ISSUE THREAD

**Issue by mw9982** [djmango/obsidian-transcription#62]
I have a Swiftink accout, and find the files are uploading correctly, but the transcriptions, summaries, etc., are not embedding under the file, like they were before. Any suggestions?

**Comment by mw9982** [comment]
Failed to mention the console shows I am getting 404 errors.  app.js:1 Uncaught (in promise) Error: Request failed, status 404
    at new t (app.js:1:2057697)
    at SK (app.js:1:2057889)
    at app.js:1:2058568
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

**Comment by mw9982** [comment]
Uncaught (in promise) Error: Request failed, status 404
    at new t (app.js:1:2057697)
    at SK (app.js:1:2057889)
    at app.js:1:2058568
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
t @ app.js:1
SK @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
setInterval (async)
eval @ plugin:obsidian-transcription:5332
getTranscriptionSwiftink @ plugin:obsidian-transcription:5322
load (async)
eval @ plugin:obsidian-transcription:4177
send @ plugin:obsidian-transcription:4176
_callee$ @ plugin:obsidian-transcription:3813
tryCatch @ plugin:obsidian-transcription:2790
eval @ plugin:obsidian-transcription:2873
eval @ plugin:obsidian-transcription:2813
asyncGeneratorStep @ plugin:obsidian-transcription:3033
_next @ plugin:obsidian-transcription:3051
eval @ plugin:obsidian-transcription:3056
eval @ plugin:obsidian-transcription:3048
sendRequest @ plugin:obsidian-transcription:3796
_sendRequest @ plugin:obsidian-transcription:3738
eval @ plugin:obsidian-transcription:3674
Promise.then (async)
_addChunkToRequest @ plugin:obsidian-transcription:3659
_performUpload @ plugin:obsidian-transcription:3632
_handleUploadResponse @ plugin:obsidian-transcription:3693
eval @ plugin:obsidian-transcription:3638
Promise.then (async)
_performUpload @ plugin:obsidian-transcription:3633
_handleUploadResponse @ plugin:obsidian-transcription:3693
eval @ plugin:obsidian-transcription:3638

**Comment by djmango** [comment]
Swiftink is shut down now unfortunately
